### ISSUE TITLE
Pictures instead of links in the loops page

### ISSUE THREAD

**Issue by Chriffe** [Jontes-Tech/floopr#7] opened 2022-11-21 19:53 UTC
I would really like to have some pictures instead of the links on the loops page. The first picture is a suggestion on how I think it should look with slightly rounded corners. And I also would like to have them displayed like this in a grid.

![layout-icons](https://user-images.githubusercontent.com/102315726/203146278-f570c676-cf16-4f02-b480-79bff10e0976.png)

The pictures:
![bass](https://user-images.githubusercontent.com/102315726/203145666-b60976f3-8961-414d-83c5-af4223d60c2b.png)
![drums](https://user-images.githubusercontent.com/102315726/203145670-856eddc3-a357-417b-876d-d73175237c89.png)
![guitar](https://user-images.githubusercontent.com/102315726/203145673-20a07628-1900-4d4b-a369-5f9eafdd7868.png)
![keys](https://user-images.githubusercontent.com/102315726/203145675-2305e044-3492-44e9-9121-9d576744c5f7.png)

Will add more pictures in the future, but let us start here for now.

**Comment by Jontes-Tech** [comment] 2022-11-21 20:18
The problem is just when someone creates a new category they would need to make a similar image.

**Comment by Chriffe** [comment] 2022-11-21 20:36
Yes, but since I will be moderating what loops that we commit, I can make new images, and or change category for the loop.

**Comment by Chriffe** [comment] 2022-11-22 05:42
Two more pictures/categories. I will not be doing anymore now until I see a need for more.

![orchestral](https://user-images.githubusercontent.com/102315726/203233866-63f1f6e3-cb1e-46b7-a13a-af2cc5c230e8.png)
![fx](https://user-images.githubusercontent.com/102315726/203233874-c0488656-8b92-4fcf-895e-fd3f0edcf05c.png)

**Comment by Chriffe** [comment] 2022-11-22 17:59
What do you mean?

Here is another category. Last one for now. Promise.
![vocals](https://user-images.githubusercontent.com/102315726/203387434-13d8c4c6-e44e-42b0-a95f-2b36216bfa4f.png)

**Comment by Jontes-Tech** [comment] 2022-11-22 18:37
I am thinking if we should just do a regular old form and then we populated the repo bypassing PRs but adding more work, or if we should keep the current workflow or if we should use a Hugo "CMS"-style frontend

**Comment by Jontes-Tech** [comment] 2022-11-23 18:56
Implemented the images, but for some reason only drums is displaying. Looking into this.

**Comment by Chriffe** [comment] 2022-11-23 20:24
Nice! Really like how the picture grows when you hover over.

However... there are som pretty nasty compression artefacts. Have you compressed the image for optimization purposes? If so, maybe we should make the picture smaller, so that it hopefully won´t be as noticeable.

**Comment by Jontes-Tech** [comment] 2022-11-24 05:39
Yes, I did compress the images. Maybe we could either make them smaller or I could just compress them less.

**Comment by Jontes-Tech** [comment] 2022-11-24 12:39
fixed, and works in prod. Closing.

**Closed by Jontes-Tech** 2022-11-24 12:39 UTC
